on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: 9.0.1
          cabal-version: 3.4
      - run: cabal update
      - run: cabal install --lib HUnit
      - run: ./run_tests.sh
